Organobusca/Organobusca/Controllers/CadastrarController.cs
using Organobusca.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Organobusca.Controllers
{
    public class CadastrarController : Controller
    {
        // GET: Cadastrar
        private dbOrg db = new dbOrg();
        public ActionResult Index()
        {
            var SESSAO = Session["usuario"];
            if (SESSAO != null)
            {
                if (SESSAO is Feirante)
                    return RedirectToAction("IndexFeirante", "Dashboard");
                else if (SESSAO is Cliente)
                    return RedirectToAction("Index", "Dashboard");
            }
            return View();
        }

        public ActionResult Cliente()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Cliente(Cliente c)
        {
            if (ModelState.IsValid)
            {     
                if (db.Cliente.FirstOrDefault(a => a.email == c.email) == null)
                {
                    db.Cliente.Add(c);
                    db.SaveChanges();
                    TempData["mensagem"] = "Cadastrado com sucesso!";
                    return RedirectToAction("Index", "Dashboard");
                }
                ModelState.AddModelError("", "Email já cadastrado.");
                return View();
            }
            return View();
        }

        public ActionResult Feirante()
        {
            dbOrg db = new dbOrg();
            ViewBag.listaFeiras = db.Feira.ToList();
            return View();
        }

        [HttpPost]
        public ActionResult Feirante(Feirante f)
        {
            if (ModelState.IsValid)
            {
                ViewBag.Feira_id = new SelectList(db.Feira.ToList(), "id", "nome");
                if (db.Feirante.FirstOrDefault(a => a.email == f.email) == null)
                {
                    db.Feirante.Add(f);
                    db.SaveChanges();
                    TempData["mensagem"] = "Cadastrado com sucesso!";
                    return RedirectToAction("Index", "Dashboard");
                }
                ModelState.AddModelError("", "Email já cadastrado.");
                return View();
            }
            return View();
        }
    }
}

Organobusca/Organobusca/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Organobusca.Models;

namespace Organobusca.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            var SESSAO = Session["usuario"];
            if (SESSAO != null)
            {
                if (SESSAO is Feirante)
                    return RedirectToAction("IndexFeirante", "Dashboard");
                else if (SESSAO is Cliente)
                    return RedirectToAction("Index", "Dashboard");
            }
            return View();

            //if(Session["cliente"] != null)
            //{
            //    return RedirectToAction("Index", "Dashboard");
            //}
            //else if (Session["feirante"] != null)
            //{
            //    return RedirectToAction("IndexFeirante", "Dashboard");
            //}
            //return View();
        }
    }
}

Organobusca/Organobusca/Controllers/LoginController.cs
using Organobusca.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Organobusca.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        private dbOrg db = new dbOrg();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult login()
        {
            var SESSAO = Session["usuario"];
            if (SESSAO != null)
            {
                if (SESSAO is Feirante)
                    return RedirectToAction("IndexFeirante", "Dashboard");
                else if (SESSAO is Cliente)
                    return RedirectToAction("Index", "Dashboard");
            }
            return View();
        }
        [HttpPost]
        public ActionResult login(string email, string senha)
        {
            if (ModelState.IsValid)
            {
                var v = db.Cliente.Where(a => a.email.Equals(email) && a.senha.Equals(senha)).FirstOrDefault();
                var f = db.Feirante.Where(a => a.email.Equals(email) && a.senha.Equals(senha)).FirstOrDefault();

                if (v != null || f != null)
                {
                    string nome = string.Empty;

                    if (v != null)
                    {   
                        Session["usuario"] = v;
                        nome = v.nome;
                        FormsAuthentication.RedirectFromLoginPage(nome, false);
                        return RedirectToAction("Index", "Dashboard");
                    }
                    else if (f != null)
                    {
                        Session["usuario"] = f;
                        nome = f.nome;
                        FormsAuthentication.RedirectFromLoginPage(nome, false);
                        return RedirectToAction("IndexFeirante", "Dashboard");
                    }
                    return View();
                }
            }
            ModelState.AddModelError("", "Login ou senha inválido!");
            return View();
        }
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            Session.Clear();
            return RedirectToAction("Index", "Home");
        }
    }
}

Organobusca/Organobusca/Views/Home/Index.cshtml

@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="~/Content/Images/favicon.ico">

    <title>Organobusca</title>

    <!-- Bootstrap core CSS -->
    <!--<link href="~/Content/bootstrap.min.css" rel="stylesheet"> -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />

    <!-- Custom styles for this template -->
    <link href="~/Content/cover.css" rel="stylesheet">
    <link href="~/Content/Site.css" rel="stylesheet">
</head>

<body>
    <div>
        @TempData["mensagem"]
    </div>
    <div class="site-wrapper">

        <div class="site-wrapper-inner">

            <div class="cover-container">

                <div class="masthead clearfix">
                    <div class="inner">
                        <h3 class="masthead-brand">
                            <img src="~/Content/Images/logo.png" alt="Organobusca" />
                        </h3>
                        <nav>
                            <ul class="nav masthead-nav">
                                <li><a href="@Url.Action("login", "Login")">Login</a></li>
                            </ul>
                        </nav>
                    </div>
                </div>

                <div class="inner cover">
                    <h1 class="cover-heading">Encontre orgânicos facilmente.</h1>
                    <p class="lead">Busque produtos orgânicos em várias feiras do Recife ou promova sua venda de orgânicos conectando-se a clientes prósperos.</p>
                    <p class="lead">
                        <a href="@Url.Action("Index", "Cadastrar")" class="btn btn-lg btn-default btn-cadastro">Cadastre-se</a>
                        <p>Já tem uma conta? @Html.ActionLink("Entre agora", "Login", "Login")</p>
                    </p>
                </div>

                <div class="mastfoot">
                    <div class="inner">
                        <p>Organobusca - Copyright 2017.</p>
                    </div>
                </div>

            </div>

        </div>

    </div>

    
</body>
</html>