Organobusca/Organobusca/Controllers/EditarController.cs
using Organobusca.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Organobusca.Controllers
{
    public class EditarController : Controller
    {
        // GET: Editar
        private dbOrg db = new dbOrg();
        [Authorize]
        public ActionResult Index()
        {
            int id = 0;
            var session = Session["usuario"];

            if (session is Cliente)
            {
                id = ((Cliente)session).id;
                var result = db.Cliente.Find(id);
                    result.confirmaSenha = result.senha;
                return View("IndexCliente", result);
            }
            else if (session is Feirante)
            {
                id = ((Feirante)session).id;
                var result = db.Feirante.Find(id);
                     result.confirmaSenha = result.senha;
                return View("IndexFeirante", result);
            }
            else
            {
                return View("IndexCliente");
            }
        }
        [HttpPost]
        public ActionResult IndexCliente(Cliente c, string NovaSenha, string NovoConfirmaSenha)
        {
            if (ModelState.IsValid && NovoConfirmaSenha == NovaSenha )
            {
                if (!string.IsNullOrEmpty(NovaSenha) && NovaSenha != c.senha)
                {
                    c.senha = NovaSenha;
                }

                db.Cliente.Attach(c);
                db.Entry(c).State = EntityState.Modified;
                db.SaveChanges();
                Session["usuario"] = c;
                TempData["mensagem"] = "Alterado com sucesso!";
                return RedirectToAction("Index", "Dashboard");
            }

            return View("IndexCliente");
        }
        [HttpPost]
        public ActionResult IndexFeirante(Feirante f, string NovaSenha, string NovoConfirmaSenha)
        {
            if (ModelState.IsValid && NovoConfirmaSenha == NovaSenha)
            {
                if (!string.IsNullOrEmpty(NovaSenha) && NovaSenha != f.senha)
                {
                    f.senha = NovaSenha;
                }

                db.Feirante.Attach(f);
                db.Entry(f).State = EntityState.Modified;
                db.SaveChanges();
                Session["usuario"] = f;
                TempData["mensagem"] = "Alterado com sucesso!";
                return RedirectToAction("IndexFeirante", "Dashboard");
            }

            return View("IndexFeirante");
        }
        [Authorize(Roles = "cliente")]
        public ActionResult DeletarCliente(int id)
        {
            var cliente = db.Cliente.Where(a => a.id == id).FirstOrDefault();
            db.Cliente.Remove(cliente);
            db.SaveChanges();
            FormsAuthentication.SignOut();
            Session.Clear();
            TempData["mensagem"] = "Usuário deletado!";
            return RedirectToAction("Index", "Home");
        }
        [Authorize(Roles = "feirante")]
        public ActionResult DeletarFeirante(int id)
        {
            var feirante = db.Feirante.Where(a => a.id == id).FirstOrDefault();
            db.Feirante.Remove(feirante);
            db.SaveChanges();
            FormsAuthentication.SignOut();
            Session.Clear();
            TempData["mensagem"] = "Usuário deletado!";
            return RedirectToAction("Index", "Home");
        }
    }
}

Organobusca/Organobusca/Controllers/FeiraController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Organobusca.Models;

namespace Organobusca.Controllers
{
    public class FeiraController : Controller
    {
        // GET: Feira
        private dbOrg db = new dbOrg();
        
        public ActionResult Index()
        {
            return RedirectToAction("Listar");
        }
        [Authorize(Roles = "feirante")]
        public ActionResult Criar()
        {
            return View();
        }
        [HttpPost]
        [Authorize(Roles = "feirante")]
        public ActionResult Criar(Feira f, int[] dia, TimeSpan[] hora_inicio, TimeSpan[] hora_fim)
        {
            for(int i = 0; i < dia.Length; i++)
            {
                DiaDaSemana horarioDia = new DiaDaSemana();
                horarioDia.dia = dia[i];
                horarioDia.hora_inicio = hora_inicio[i];
                horarioDia.hora_fim = hora_fim[i];
                horarioDia.Feira_id = f.id;

                db.DiaDaSemana.Add(horarioDia);
            }
            db.Feira.Add(f);
            db.SaveChanges();
            return RedirectToAction("Listar");
        }
        [Authorize(Roles = "feirante")]
        public ActionResult Listar()
        {
            return View(db.Feira.ToList());
        }
        [Authorize(Roles = "feirante")]
        public ActionResult Excluir(int id)
        {
            var feira = db.Feira.Where(m => m.id == id).FirstOrDefault();
            
            var dia = db.DiaDaSemana.Where(d => d.Feira_id == feira.id).ToList();
            db.DiaDaSemana.RemoveRange(dia);

            db.Feira.Remove(feira);
            db.SaveChanges();
            return RedirectToAction("Listar");
        }
    }
}

Organobusca/Organobusca/Views/Feira/Criar.cshtml
@model Organobusca.Models.Feira

@{
    ViewBag.Title = "Criar nova feira";
    Layout = "~/Views/Shared/_DashboardFeiranteLayout.cshtml";
}
<style>
    #map {
        width: 100%;
        height: 280px;
        padding: 10px;
    }
</style>
<h2>Criar nova feira</h2>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Localização</label>
            <div class="col-md-10">
                <input id="autocomplete" class="form-control" type="text" placeholder="Digite endereço">
                <input id="submit" value="Encontrar" type="button" class="btn btn-success">
                <div id="map"></div>
                <div class="form-group">
                    <input type="hidden" name="latitude" id="latitude" placeholder="latitude" />
                    <input type="hidden" name="longitude" id="longitude" placeholder="longitude"/>
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.rua, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.rua, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.rua, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.bairro, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.bairro, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.bairro, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cidade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cidade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cidade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cep, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cep, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cep, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.numero, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.numero, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.numero, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Horário de funcionamento</label>
            <div class="col-md-10">
                <div id="diascp"></div>
                <button type="button" class="btn btn-success add">Novo horário</button>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Criar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div id="modelo-dia" class="form-group" style="display: none;">
    <div>
        <select name="dia[]">
            <option value="1">Domingo</option>
            <option value="2">Segunda-feira</option>
            <option value="3">Terça-feira</option>
            <option value="4">Quarta-feira</option>
            <option value="5">Quinta-feira</option>
            <option value="6">Sexta-feira</option>
            <option value="7">Sábado </option>
        </select>

        <label for="hora_inicio">Hora início</label>
        <input name="hora_inicio[]" type="time" />

        <label for="hora_inicio">Hora fim</label>
        <input name="hora_fim[]" type="time" />

        <button type="button" class="btn btn-success excluir">Excluir</button>
    </div>
</div>

@section scripts
{
    <script>
        var numeroDeHorarios = 0;
        function adicionarDia() {
            var teste = $("#modelo-dia").clone();
            numeroDeHorarios += 1;
            teste.attr("id", "dia" + String(numeroDeHorarios));
            $("#diascp").append(teste.show());
        }
        $(document).ready(function () {
            $(".add").click(adicionarDia);
            $(document).on("click", ".excluir", function () {
                numeroDeHorarios -= 1;
                $(this).parent().remove();
            });
        });
    </script>
    <script>
        function initMap() {

            var geocoder = new google.maps.Geocoder();

            var autocomplete = new google.maps.places.Autocomplete(
                document.getElementById('autocomplete'), { types: ['geocode'] });

            var map = new google.maps.Map(document.getElementById('map'), {
                center: { lat: -8.0624203, lng: -34.9270747 }, /* Recife */
                zoom: 13
            })

            marker = new google.maps.Marker({
                map: map,
                position: { lat: 0, lng: 0 },
                draggable: true
            });
            marker.setVisible(false);

            var infowindow = new google.maps.InfoWindow;

            /* mudar marker ao digitar endereco */
            document.getElementById('submit').addEventListener('click', function () { addressToGeocode(geocoder, map); });
            function addressToGeocode(geocoder, map) {
                console.log(autocomplete.getPlace());
                var address = autocomplete.getPlace().formatted_address;
                geocoder.geocode({ 'address': address }, function (results, status) {
                    if (status == 'OK') {
                        map.setCenter(results[0].geometry.location);
                        marker.setVisible(true);
                        marker.setPosition(results[0].geometry.location);
                        map.setZoom(17);
                        infowindow.setContent(results[0].formatted_address);
                        infowindow.open(map, marker);
                        fillAddressFields(results[0]);
                    } else {
                        alert("Nenhum lugar encontrado com esse endereço");
                    }
                });

            }

            /* mudar endereco ao arrastar marker*/
            google.maps.event.addListener(marker, 'dragend', function (evt) {
                var location = {
                    lat: evt.latLng.lat(),
                    lng: evt.latLng.lng()
                }
                geocodeToAddress(geocoder, map, infowindow, location);
            });

            function geocodeToAddress(geocoder, map, infowindow, location) {
                geocoder.geocode({ 'location': location }, function (results, status) {
                    if (status == 'OK') {
                        if (results[1]) {
                            infowindow.setContent(results[1].formatted_address);
                            infowindow.open(map, marker);
                            fillAddressFields(results[1]);
                        } else {
                            alert("Local não encontrado");
                        }
                    } else {
                        alert("Geocoder falhou");
                    }
                });
            }

            function fillAddressFields(results) {
                var latlng = [results.geometry.location.lat(), results.geometry.location.lng()];
                document.getElementById("latitude").value = latlng[0].toString().replace('.', ',');
                document.getElementById("longitude").value = latlng[1].toString().replace('.', ',');
            }
        }
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAs3V5BDT2RqWxKznEvIBdT4WKNQ5_lLf0&libraries=places&callback=initMap" async defer></script>
}
<div>
</div>

Organobusca/Organobusca/Views/Feira/Listar.cshtml
@model List<Organobusca.Models.Feira>

@{
    ViewBag.Title = "Listar feiras";
    Layout = "~/Views/Shared/_DashboardFeiranteLayout.cshtml";
}

<div style="display:inline-block;"><h2>Todas as feiras</h2></div>
<div style="display:inline-block; float:right;">
    @Html.ActionLink("Criar", "Criar", null, new { @class = "btn btn-success" })
</div>

<table class="table">
    <thead>
        <th><b>Nome</b></th>
        <th><b>Rua</b></th>
        <th><b>Cidade</b></th>
        <!-- <th><b>Bairro</b></th> -->
        <th><b>CEP</b></th>
        <th><b>Horário de funcionamento</b></th>
        <th></th>
    </thead>
    <tbody>
    @if (Model != null)
    {
        string[] semana = { "", "Domingo", "Segunda", "Terça", "Quarta", "Quinta", "Sexta", "Sábado" };

        foreach (var item in Model)
        {
            <tr>
                <td>@item.nome</td>
                <td>@item.rua</td>
                <td>@item.cidade</td>
                <td>@item.cep</td>
                <td>
                    @foreach (var dia in item.DiaDaSemana)
                    {
                        string campo = semana[@dia.dia] + " das " + @dia.hora_inicio.ToString(@"hh\:mm") + "h às " + @dia.hora_fim.ToString(@"hh\:mm") + "h";
                        <div>@campo</div>
                    }
                </td>
                <td>@Html.ActionLink("Excluir", "Excluir", "Feira", new { id= item.id }, null)</td>



            </tr>
        }
    }
    </tbody>

</table>
@*<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.nome)
        </th>
        <td>
            @Html.DisplayFor(model => model.nome)
        </td>
        <th>
            @Html.DisplayNameFor(model => model.bairro)
        </th>
        <td>
            @Html.DisplayFor(model => model.bairro)
        </td>
        <th>
            @Html.DisplayNameFor(model => model.cidade)
        </th>
        <td>
            @Html.DisplayFor(model => model.cidade)
        </td>
        <th>
            @Html.DisplayNameFor(model => model.rua)
        </th>
        <td>
            @Html.DisplayFor(model => model.rua)
        </td>
        <th>
            @Html.DisplayNameFor(model => model.cep)
        </th>
        <td>
            @Html.DisplayFor(model => model.cep)
        </td>
        <th>
            @Html.DisplayNameFor(model => model.numero)
        </th>
        <td>
            @Html.DisplayFor(model => model.numero)
        </td>
        <th>
            @Html.DisplayNameFor(model => model.longitude)
        </th>
        <td>
            @Html.DisplayFor(model => model.longitude)
        </td>
        <th>
            @Html.DisplayNameFor(model => model.latitude)
        </th>
        <td>
            @Html.DisplayFor(model => model.latitude)
        </td>
        @*<th>
            @Html.ActionLink("Edit", "Editar", new { id = item.id }) |
            @Html.ActionLink("Detalhes", "Detalhes", new { id = item.id }) |
            @Html.ActionLink("Apagar", "Delet", new { id = item.id })
        </th>*@
        @*<th></th>
    </tr>
</table>*@