Organobusca/Organobusca/Controllers/ContaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Organobusca.Models;

namespace Organobusca.Controllers
{
    public class ContaController : Controller
    {
        // GET: Conta
        public ActionResult Index()
        {
            if(Session["usuario"] is Cliente)
            {
                return RedirectToAction("Cliente");
            }
            else
            {
                return RedirectToAction("Feirante");
            }
        }
        [Authorize(Roles ="cliente")]
        public ActionResult Cliente()
        {
            return View(Session["usuario"]);
        }
        [Authorize(Roles = "feirante")]
        public ActionResult Feirante()
        {
            return View(Session["usuario"]);
        }
    }
}

Organobusca/Organobusca/Controllers/FeiraController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Organobusca.Models;

namespace Organobusca.Controllers
{
    public class FeiraController : Controller
    {
        // GET: Feira
        private dbOrg db = new dbOrg();
        
        public ActionResult Index()
        {
            return RedirectToAction("Listar");
        }
        [Authorize(Roles = "feirante")]
        public ActionResult Criar()
        {
            return View();
        }
        [HttpPost]
        [Authorize(Roles = "feirante")]
        public ActionResult Criar(Feira f, int[] dia, TimeSpan[] hora_inicio, TimeSpan[] hora_fim)
        {
            for(int i = 0; i < dia.Length; i++)
            {
                DiaDaSemana horarioDia = new DiaDaSemana();
                horarioDia.dia = dia[i];
                horarioDia.hora_inicio = hora_inicio[i];
                horarioDia.hora_fim = hora_fim[i];
                horarioDia.Feira_id = f.id;

                db.DiaDaSemana.Add(horarioDia);
            }
            db.Feira.Add(f);
            db.SaveChanges();
            return RedirectToAction("Listar");
        }
        [Authorize(Roles = "feirante")]
        public ActionResult Listar()
        {
            return View(db.Feira.ToList());
        }
        [Authorize(Roles = "feirante")]
        public ActionResult Excluir(int id)
        {
            var feira = db.Feira.Where(m => m.id == id).FirstOrDefault();
            
            var dia = db.DiaDaSemana.Where(d => d.Feira_id == feira.id).ToList();
            db.DiaDaSemana.RemoveRange(dia);

            db.Feira.Remove(feira);
            db.SaveChanges();
            return RedirectToAction("Listar");
        }
    }
}

Organobusca/Organobusca/Controllers/LoginController.cs
using Organobusca.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Organobusca.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        private dbOrg db = new dbOrg();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult login()
        {
            var SESSAO = Session["usuario"];
            if (SESSAO != null)
            {
                if (SESSAO is Feirante)
                    return RedirectToAction("IndexFeirante", "Dashboard");
                else if (SESSAO is Cliente)
                    return RedirectToAction("Index", "Dashboard");
            }
            return View();
        }
        [HttpPost]
        public ActionResult login(string email, string senha)
        {
            if (ModelState.IsValid)
            {
                var v = db.Cliente.Where(a => a.email.Equals(email) && a.senha.Equals(senha)).FirstOrDefault();
                var f = db.Feirante.Where(a => a.email.Equals(email) && a.senha.Equals(senha)).FirstOrDefault();

                if (v != null || f != null)
                {
                    string nome = string.Empty;

                    if (v != null)
                    {   
                        Session["usuario"] = v;
                        nome = v.nome;
                        FormsAuthentication.RedirectFromLoginPage(nome, false);
                        return RedirectToAction("Index", "Dashboard");
                    }
                    else if (f != null)
                    {
                        Session["usuario"] = f;
                        nome = f.nome;
                        FormsAuthentication.RedirectFromLoginPage(nome, false);
                        return RedirectToAction("IndexFeirante", "Dashboard");
                    }
                    return View();
                }
            }
            ModelState.AddModelError("", "Login ou senha inválido!");
            return View();
        }
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            Session.Clear();
            return RedirectToAction("Index", "Home");
        }
    }
}

Organobusca/Organobusca/Views/Shared/_DashboardClienteLayout.cshtml
@using Organobusca.Util
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>@ViewBag.Title | Organobusca</title>

    <!-- Bootstrap core CSS -->
    <!--<link href="~/Content/bootstrap.min.css" rel="stylesheet"> -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />

    <!-- Custom styles for this template -->
    <link href="~/Content/dashboard.css" rel="stylesheet">
    <link href="~/Content/Site.css" rel="stylesheet">
    <link href="carousel.css" rel="stylesheet">

</head>

<body>
    <nav class="navbar navbar-inverse navbar-fixed-top ob-navbar">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">
                    <img src="~/Content/Images/logo.png" alt="Organobusca" />
                </a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#">Dashboard</a></li>
                    <li class="dropdown">
                        @*@HttpContext.Current.User.Identity.Name*@
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">@Html.GetUserName(HttpContext.Current.Session) <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Minha conta", "Cliente", "Conta")</li> 
                            <li>@Html.ActionLink("Sair", "Logout", "Login")</li>
                        </ul>
                    </li>
                </ul>
                <form class="navbar-form navbar-right">
                    <input type="text" class="form-control" placeholder="Pesquisar feiras...">
                </form>
            </div>
        </div>
    </nav>
    
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-3 col-md-2 sidebar">
                <ul class="nav nav-sidebar">

                    <li class="active"><a href="@Url.Action("Index", "Dashboard")"><span class="glyphicon glyphicon-leaf"></span>Dashboard <span class="sr-only">(current)</span></a></li>
                    <li><a href="@Url.Action("Cliente","Conta")"><span class="glyphicon glyphicon-user"></span>Minha conta</a></li>
                    <li><a href="@Url.Action("panorama","Dashboard")"><span class="glyphicon glyphicon-wrench"></span>Novidades</a></li>
                    <li><a href="@Url.Action("ajudaCliente", "Dashboard")"><span class="glyphicon glyphicon-question-sign"></span>Ajuda</a></li>
                </ul>
                <br />
                <br />
                <br />
                <img width="170" height="170" src="http://www.portaltribunadonorte.com/images/publicidades/1701481117.jpg" />
            </div>
            
            <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
                @RenderBody()
            </div>
        </div>
    </div>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    @RenderSection("scripts", false)
</body>
</html>

Organobusca/Organobusca/Views/Shared/_DashboardFeiranteLayout.cshtml
@using Organobusca.Util
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>@ViewBag.Title | Organobusca</title>

    <!-- Bootstrap core CSS -->
    <!--<link href="~/Content/bootstrap.min.css" rel="stylesheet"> -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />

    <!-- Custom styles for this template -->
    <link href="~/Content/dashboard.css" rel="stylesheet">
    <link href="~/Content/Site.css" rel="stylesheet">

</head>

<body>
    <nav class="navbar navbar-inverse navbar-fixed-top ob-navbar">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">
                    <img src="~/Content/Images/logo.png" alt="Organobusca" />
                </a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#">Dashboard</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">@Html.GetUserName(HttpContext.Current.Session) <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Minha conta", "Feirante", "Conta")</li> 
                            <li><a href="@Url.Action("Listar", "Feira")">Feiras</a></li>
                            <li>@Html.ActionLink("Sair", "Logout", "Login")</li>
                        </ul>
                    </li>
                </ul>
                <form class="navbar-form navbar-right">
                    <input type="text" class="form-control" placeholder="Pesquisar feiras...">
                </form>
            </div>
        </div>
    </nav>

    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-3 col-md-2 sidebar">
                <ul class="nav nav-sidebar">

                    <li class="active"><a href="@Url.Action("IndexFeirante", "Dashboard")"><span class="glyphicon glyphicon-leaf"></span>Dashboard <span class="sr-only">(current)</span></a></li>
                    <li><a href=""><span class="glyphicon glyphicon-user"></span>Meus produtos **</a></li>
                    <li><a href="@Url.Action("Listar", "Feira")"><span class="glyphicon glyphicon-check"></span>Feiras</a></li>
                    <li><a href="@Url.Action("Feirante", "Conta")"><span class="glyphicon glyphicon-wrench"></span>Minha conta</a></li>
                    <li><a href="@Url.Action("ajudaFeirante","Dashboard")"><span class="glyphicon glyphicon-question-sign"></span>Ajuda</a></li>
                </ul>
                <br />
                <br />
                <br />
                <img width="170" height="170" src="http://www.portaltribunadonorte.com/images/publicidades/1701481117.jpg" />
            </div>
            <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
                @RenderBody()
            </div>
        </div>
    </div>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    @RenderSection("scripts", false)
</body>
</html>